import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar'
import Page from './Components/About/page'
import Services from './Services/Page'
import Contact from './Components/Contact'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}  >{children}
      <div className='overflow-x-hidden'>
      <Navbar/>

<Page/>
<Services/>
<Contact/>
</div>
      </body>
    </html>
  )
}
